name: Jackyxie Docker Image Building

on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Build the Docker image
      uses: docker/build-push-action@v1
      with:
        name: jackyxie/java-tron
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true
